import { useState } from 'react'
import { Link } from 'react-router-dom'
import { places, categories, photo } from '../data'
export default function Home(){
 const [search,setSearch]=useState('');const [category,setCategory]=useState('Tümü')
 const filtered=places.filter(p=>(category==='Tümü'||p.category===category)&&p.title.toLocaleLowerCase('tr-TR').includes(search.trim().toLocaleLowerCase('tr-TR')))
 return <><section className="hero" style={{backgroundImage:`linear-gradient(#0008,#0009),url(${photo('photo-1507525428034-b723cf961d3e',1800)})`}}><div className="hero-content"><span className="eyebrow">Seyahat ve Gezi Rehberi</span><h1>Dünyayı Keşfet</h1><p>Yeni şehirler, tarihi yerler ve eşsiz doğa manzaraları seni bekliyor.</p><a className="button" href="#rotalar">Keşfetmeye Başla</a><div className="stats"><div><strong>4</strong><span>Örnek Rota</span></div><div><strong>4</strong><span>Gezi Kategorisi</span></div><div><strong>3</strong><span>Rehber Yazısı</span></div></div></div></section>
 <section className="container section" id="rotalar"><div className="section-heading"><h2>Rotaları Keşfet</h2><p>İlgi alanına göre filtrele veya bir yer ara.</p></div><div className="filters">{categories.map(c=><button className={category===c?'filter active':'filter'} key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div><label className="search-label">Rota ara<input type="search" placeholder="Örneğin: Kapadokya" value={search} onChange={e=>setSearch(e.target.value)}/></label><p className="result-count" role="status">{filtered.length} rota bulundu</p><div className="cards">{filtered.map(p=><article className="card" key={p.id}><img src={photo(p.image,800)} alt={`${p.title} için temsili gezi fotoğrafı`} loading="lazy"/><div className="card-body"><span className="tag">{p.category}</span><h3>{p.title}</h3><p>{p.description}</p><Link className="button" to={`/rotalar/${p.id}`}>Detay Gör</Link></div></article>)}</div>{filtered.length===0&&<div className="empty"><p>Aramana uygun rota bulunamadı.</p><button className="button" onClick={()=>{setSearch('');setCategory('Tümü')}}>Filtreleri temizle</button></div>}</section></>
}
