export const places = [
 {id:'kapadokya',title:'Kapadokya',category:'Tarihi',image:'photo-1544735716-392fe2489ffa',description:'Peribacaları, vadiler ve kaya yerleşimleriyle tanınan Kapadokya, yürüyüş ve kültür gezileri için bir rota sunar.',tips:'Göreme ve Uçhisar çevresini keşfedebilir, vadi yürüyüşlerini hava koşullarına göre planlayabilirsin.',position:[38.6431,34.8289]},
 {id:'paris',title:'Paris',category:'Şehir',image:'photo-1502602898657-3e91760cbb34',description:'Paris; müzeleri, mimarisi ve Seine kıyısındaki yürüyüş yollarıyla keşfedilebilir.',tips:'Müze ziyaretlerini önceden planla. Şehri yürüyerek ve toplu taşımayla keşfet.',position:[48.8566,2.3522]},
 {id:'maldivler',title:'Maldivler',category:'Deniz',image:'photo-1507525428034-b723cf961d3e',description:'Maldivler, Hint Okyanusu’ndaki adaları ve deniz aktiviteleriyle tanınır.',tips:'Ada transferlerini, hava koşullarını ve konaklama seçeneklerini seyahatten önce kontrol et.',position:[4.1755,73.5093]},
 {id:'bolu',title:'Bolu',category:'Doğa',image:'photo-1470770903676-69b98201ea1c',description:'Bolu çevresindeki göller ve ormanlar doğa yürüyüşleri için farklı seçenekler sunar.',tips:'Yürüyüş için uygun ayakkabı kullan; koruma alanlarında işaretli yolları takip et.',position:[40.735,31.6061]}
]
export const categories = ['Tümü','Tarihi','Doğa','Şehir','Deniz']
export const photo = (id, width=1000) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=80`
export const articles = [
 {id:'sehir',title:'Şehir Gezisi Nasıl Planlanır?',image:'photo-1502602898657-3e91760cbb34',summary:'Kısa bir gezide zamanını verimli kullanmak için basit öneriler.',paragraphs:['Önce görmek istediğin yerleri bir listeye yaz. Birbirine yakın noktaları aynı güne koyarak ulaşım süresini azaltabilirsin.','Müze ve etkinliklerin açık olduğu günleri kontrol et. Rezervasyon gerektiren yerler için önceden hazırlık yap.','Her günü tamamen doldurma. Dinlenmek, yemek yemek ve beklenmedik keşifler için zaman ayır.']},
 {id:'kamp',title:'Doğa Gezisi İçin Hazırlık',image:'photo-1470770903676-69b98201ea1c',summary:'Yürüyüş öncesinde hava, ekipman ve rota kontrolü.',paragraphs:['Hava tahminini ve parkurun koşullarını kontrol ederek başlayabilirsin. Rotanın zorluğunu deneyimine göre seç.','Su, uygun ayakkabı ve hava koşullarına uygun kıyafetler hazırla. Telefonunun şarjını ve çevrimdışı haritanı kontrol et.','İşaretli yolları takip et, çöplerini yanında götür ve doğaya zarar verme.']},
 {id:'deniz',title:'Deniz Tatili İçin Küçük İpuçları',image:'photo-1507525428034-b723cf961d3e',summary:'Ulaşım ve konaklamayı planlarken nelere bakabilirsin?',paragraphs:['Konaklama seçerken sadece fotoğraflara değil, ulaşım olanaklarına ve güncel değerlendirmelere de bak.','Plajın koşullarını ve yerel uyarıları kontrol et. Güneşten korunmayı ve su içmeyi unutma.','Rezervasyonun iptal koşullarını oku ve bütçene ulaşım ile yemek masraflarını da ekle.']}
]
